-d C:\wks\ework\FPGA\TangNano\20k\TangNanoZ80MEMCPM\TangNanoZ80MEMCPM_project\impl\gwsynthesis\TangNanoZ80MEMCPM_project.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\wks\ework\FPGA\TangNano\20k\TangNanoZ80MEMCPM\TangNanoZ80MEMCPM_project\src\tn20k.cst
-cfg C:\wks\ework\FPGA\TangNano\20k\TangNanoZ80MEMCPM\TangNanoZ80MEMCPM_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
