M48
; DRILL file {KiCad 8.0.4} date 2024-08-20T14:56:40+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-20T14:56:40+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X0.2064Y-0.2
X0.2064Y-2.7
X2.7064Y-0.2
X2.7064Y-2.7
M30
