-d C:\wks\ework\FPGA\TangNano\9k\TangNanoZ80MEM\TangNanoZ80MEM_project\impl\gwsynthesis\TangNanoZ80MEM_project.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\wks\ework\FPGA\TangNano\9k\TangNanoZ80MEM\TangNanoZ80MEM_project\src\tn9k.cst
-cfg C:\wks\ework\FPGA\TangNano\9k\TangNanoZ80MEM\TangNanoZ80MEM_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
